### ISSUE TITLE
关于如何集成到React Native

### ISSUE THREAD

**Issue by Macrow** [netless-io/docs#168]
我们想集成Netless的白板产品到我们的App，App使用React Native开发，经过尝试，发现使用white-react-sdk会有一些问题，麻烦请问一下，关于集成到React Native，你有什么建议吗？

**Comment by leavesster** [comment]
有几种思路：

1. 在 React-Native 中使用 webview 来展示白板。然后通过 RN 提供的 API 来与 webview 交互。
2. 分别封装 iOS Android 两端的 native sdk 桥接 RN。

你们应该是使用了第一种方式，这种方式是比较合适。native sdk 其实也是 webview + native js bridge 的做法。
你们使用 white-react-sdk 的时候，具体有什么问题呢？

**Comment by Macrow** [comment]
非常感谢回复，如果你说的native sdk也是调用webview + native js bridge的话，我再分别封装 iOS Android 两端的 native sdk 桥接 RN就意义不大了。

我看了你们的
https://github.com/netless-io/white-fast-web-sdk
其实可以直接用的，节约开发成本，我想问一下，截图这个地方有地方可以屏蔽吗？找了半天没找到地方。

![F07E554E-45A2-4EC5-B2E9-6F3A26E8C1C6](https://user-images.githubusercontent.com/240792/71912762-16d12880-31b1-11ea-9b21-00b17b457fa1.png)

**Comment by Macrow** [comment]
我暂时用css的方法隐藏了
