### ISSUE TITLE
API版本疑问

### ISSUE THREAD

**Issue by AdamFu** [netless-io/docs#303]
前几天看到官方的文档和API地址跟现在的是不一样的。前几天看到的是https://shunt-api.netless.link/v5的，为什么现在看到的又是旧的？ 是准备切换新版了吗？

**Comment by leavesster** [comment]
最近在切换新版本，2.9.0 新版本会使用新的 API ，旧 API 会保持兼容。

**Comment by AdamFu** [comment]
@leavesster 好的，谢谢。请问，新版大概什么时候上线呢？我们这边正准备接入，如果有新版就不接旧版了。

**Comment by leavesster** [comment]
web已经发布2.9.1版本，native 2.9.0版本会在这周发布。这些了连接都会指向新版本服务器地址。

主要也是服务器api的改动，服务器api也会在这两周内发布。内部已经通过验证的测试。
您可以直接先接入web版，sdk内部提供types定义。

**Comment by AdamFu** [comment]
@leavesster 好的，那没问题。我这边服务器api已经接入了目前版本了，如果更新后端进行更换就行。前端web的sdk升级了就好。非常感谢你的解答
